wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1637678350
    t:
      1:
      - 1
      - 5
      4: 3.7.12
      5: 0.12.7
      8:
      - 5
